Repository kesshoban3310/OOPL2024S, pull requests merged in 2024-03, with the labels that each got.

#1 remove useless markdown
  README.md
Labels: documentation

#2 add format file and apply changes to files
  .clang-format
  src/App.cpp
  src/main.cpp
Labels: enhancement

#3 Add github actions to check availability
  .github/workflows/cmake-multi-platform.yml
Labels: enhancement

#5 Remove unnecessary assets
  Resources/Picture/Boss/Dr Wily.png
  Resources/Picture/Boss/Wily Castle Bosses.png
  Resources/Picture/Miscellaneous/Dr Light and Roll.png
Labels: enhancement

#19 新增註解以及檔案
  Resources/Map/test.txt
  files.cmake
  include/App.hpp
  include/BackGroundImage.hpp
  include/BackGroundMap.hpp
  include/Component/Backgroundmap.hpp
  include/Component/Txtconverter.hpp
  src/App.cpp
  src/BackGroundImage.cpp
  src/BackGroundMap.cpp
  src/Component/Backgroundmap.cpp
  src/Component/Tilemap.cpp
  src/Component/Txtconverter.cpp
Labels: documentation, enhancement

#24 Dev character
  Resources/Map/test.txt
  Resources/Picture/Character/Normal/Death1.png
  Resources/Picture/Character/Normal/Death2.png
  Resources/Picture/Character/Normal/Death3.png
  Resources/Picture/Character/Normal/Death4.png
  Resources/Picture/Character/Normal/Walk1.png
  Resources/Picture/Character/Normal/WalkRight1.png
  Resources/Picture/Character/Normal/WalkRight2.png
  Resources/Picture/Character/Normal/WalkRight3.png
  files.cmake
  include/App.hpp
  include/Component/Backgroundmap.hpp
  include/Component/Characterattribute.hpp
  include/Component/Rockman.hpp
  src/App.cpp
  src/Component/AnimatedObject.cpp
  src/Component/Rockman.cpp
  src/Component/Tilemap.cpp
Labels: enhancement
